P8105_hw1_jam2530
================
Jenna Mohammed
September 23 2023

``` r
library(moderndive)
library(tidyverse)
```

    ## -- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --
    ## v dplyr     1.1.2     v readr     2.1.4
    ## v forcats   1.0.0     v stringr   1.5.0
    ## v ggplot2   3.4.3     v tibble    3.2.1
    ## v lubridate 1.9.2     v tidyr     1.3.0
    ## v purrr     1.0.1     
    ## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()
    ## i Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
data("early_january_weather")
```

# Problem 1

``` r
# Calculating information about table

early_january_weather
```

    ## # A tibble: 358 x 15
    ##    origin  year month   day  hour  temp  dewp humid wind_dir wind_speed
    ##    <chr>  <int> <int> <int> <int> <dbl> <dbl> <dbl>    <dbl>      <dbl>
    ##  1 EWR     2013     1     1     1  39.0  26.1  59.4      270      10.4 
    ##  2 EWR     2013     1     1     2  39.0  27.0  61.6      250       8.06
    ##  3 EWR     2013     1     1     3  39.0  28.0  64.4      240      11.5 
    ##  4 EWR     2013     1     1     4  39.9  28.0  62.2      250      12.7 
    ##  5 EWR     2013     1     1     5  39.0  28.0  64.4      260      12.7 
    ##  6 EWR     2013     1     1     6  37.9  28.0  67.2      240      11.5 
    ##  7 EWR     2013     1     1     7  39.0  28.0  64.4      240      15.0 
    ##  8 EWR     2013     1     1     8  39.9  28.0  62.2      250      10.4 
    ##  9 EWR     2013     1     1     9  39.9  28.0  62.2      260      15.0 
    ## 10 EWR     2013     1     1    10  41    28.0  59.6      260      13.8 
    ## # i 348 more rows
    ## # i 5 more variables: wind_gust <dbl>, precip <dbl>, pressure <dbl>,
    ## #   visib <dbl>, time_hour <dttm>

``` r
nrow(early_january_weather)
```

    ## [1] 358

``` r
ncol(early_january_weather)
```

    ## [1] 15

``` r
# Calculating mean of temperature

mean(pull(early_january_weather, temp))
```

    ## [1] 39.58212

Table Description: The table shows that there are 358 rows and 15
columns. Important variables in this dataset are hour, temperature,
dewpoint, humidity,wind direction, wind speed, and pressure. The
information is repeatedly collected every hour from hour 1 to hour 23.
The mean of the temperature is 39.58212

``` r
# Creating scatterplot for time_hour vs temperature

plot_df = tibble(
    x = "time_hour",
    y = "temp"

)

ggplot(early_january_weather, aes(x = time_hour , y = temp , color = humid )) + geom_point()
```

![](P8105_hw1_jam2530_files/figure-gfm/unnamed-chunk-5-1.png)<!-- -->

``` r
ggsave("P8105_hw1_jam2530.pdf")                                                                        
```

    ## Saving 7 x 5 in image

Plot Description: The plot shown expressed the relationship between
time_hour and temperature, with time_hour represented on the x axis and
temperature represented on the y axis. The graph shows a moderately
strong positive relationship. There are no apparent outliers, but around
January 12th/13th the data strayes from the pattern.

# Problem 2

This code chunk shows the creation of a data frame.

``` r
Homework_df = tibble(
        samp = rnorm(10),
        vec_logical = samp > 0,
        vec_char = c("1", "2", "3", "4" , "5" , "6" , "7", "8" , "9" , "10"),
        vec_factor = c("LOW", "MED", "HIGH", "LOW", "LOW", "MED", "HIGH", "LOW", "MED", "HIGH"),
    )
```

This code chunk will take the mean of each variable in the data frame.

``` r
# taking the mean of each variable

mean(Homework_df[["samp"]])
```

    ## [1] -0.3317109

``` r
mean(Homework_df[["vec_logical"]])
```

    ## [1] 0.3

``` r
mean(Homework_df[["vec_char"]])
```

    ## Warning in mean.default(Homework_df[["vec_char"]]): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
mean(Homework_df[["vec_factor"]])
```

    ## Warning in mean.default(Homework_df[["vec_factor"]]): argument is not numeric
    ## or logical: returning NA

    ## [1] NA

This code chunk will convert variables from one type to another.

``` r
as.numeric(Homework_df[["vec_logical"]])
```

    ##  [1] 0 0 0 1 1 0 1 0 0 0

``` r
as.numeric(Homework_df[["vec_char"]])
```

    ##  [1]  1  2  3  4  5  6  7  8  9 10

``` r
as.numeric(Homework_df[["vec_factor"]])
```

    ## Warning: NAs introduced by coercion

    ##  [1] NA NA NA NA NA NA NA NA NA NA

Mean/as.numeric description: When taking the as.numeric of “vec_factor”,
an error occurs. There is an error when trying to compute the mean for
it as well since it is categorized as “low”, “med”, and “high”. This
cannot be converted into numerical values and therefore cannot give you
a mean.
